
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace jQueryAjaxInAsp.NETMVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    public int EmployeeID { get; set; }

    public string Name { get; set; }

    public string Gender { get; set; }

    public string Office { get; set; }

    public Nullable<int> Age { get; set; }

    public Nullable<int> Email { get; set; }

    public string ImagePath { get; set; }

}

}
